// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.1
// source: goorm/rpc/v1/goorm_v1.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoormRpcV1Client is the client API for GoormRpcV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoormRpcV1Client interface {
	HttpGet(ctx context.Context, in *HttpGetRequest, opts ...grpc.CallOption) (*HttpResponse, error)
	HttpPost(ctx context.Context, in *HttpPostRequest, opts ...grpc.CallOption) (*HttpResponse, error)
}

type goormRpcV1Client struct {
	cc grpc.ClientConnInterface
}

func NewGoormRpcV1Client(cc grpc.ClientConnInterface) GoormRpcV1Client {
	return &goormRpcV1Client{cc}
}

func (c *goormRpcV1Client) HttpGet(ctx context.Context, in *HttpGetRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, "/GoormRpcV1/HttpGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goormRpcV1Client) HttpPost(ctx context.Context, in *HttpPostRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, "/GoormRpcV1/HttpPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoormRpcV1Server is the server API for GoormRpcV1 service.
// All implementations must embed UnimplementedGoormRpcV1Server
// for forward compatibility
type GoormRpcV1Server interface {
	HttpGet(context.Context, *HttpGetRequest) (*HttpResponse, error)
	HttpPost(context.Context, *HttpPostRequest) (*HttpResponse, error)
	mustEmbedUnimplementedGoormRpcV1Server()
}

// UnimplementedGoormRpcV1Server must be embedded to have forward compatible implementations.
type UnimplementedGoormRpcV1Server struct {
}

func (UnimplementedGoormRpcV1Server) HttpGet(context.Context, *HttpGetRequest) (*HttpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HttpGet not implemented")
}
func (UnimplementedGoormRpcV1Server) HttpPost(context.Context, *HttpPostRequest) (*HttpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HttpPost not implemented")
}
func (UnimplementedGoormRpcV1Server) mustEmbedUnimplementedGoormRpcV1Server() {}

// UnsafeGoormRpcV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoormRpcV1Server will
// result in compilation errors.
type UnsafeGoormRpcV1Server interface {
	mustEmbedUnimplementedGoormRpcV1Server()
}

func RegisterGoormRpcV1Server(s grpc.ServiceRegistrar, srv GoormRpcV1Server) {
	s.RegisterService(&GoormRpcV1_ServiceDesc, srv)
}

func _GoormRpcV1_HttpGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoormRpcV1Server).HttpGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoormRpcV1/HttpGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoormRpcV1Server).HttpGet(ctx, req.(*HttpGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoormRpcV1_HttpPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoormRpcV1Server).HttpPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoormRpcV1/HttpPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoormRpcV1Server).HttpPost(ctx, req.(*HttpPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoormRpcV1_ServiceDesc is the grpc.ServiceDesc for GoormRpcV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoormRpcV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GoormRpcV1",
	HandlerType: (*GoormRpcV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HttpGet",
			Handler:    _GoormRpcV1_HttpGet_Handler,
		},
		{
			MethodName: "HttpPost",
			Handler:    _GoormRpcV1_HttpPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goorm/rpc/v1/goorm_v1.proto",
}
